#! /bin/sh

## Simple script to automate common automake-related tasks

echo "== Running aclocal =="
aclocal

echo "== Running autoheader =="
autoheader

echo "== Running libtoolize =="
libtoolize --force

echo "== Running automake =="
automake -f -c --add-missing

echo "== Running autoconf =="
autoconf
